## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia -e 'using Pkg; Pkg.add(pwd()); Pkg.build("Revise"); Pkg.test("Revise"; coverage=true)'
  - JULIA_REVISE_POLL=1 julia --code-coverage -e 'using Pkg; include(Pkg.dir("Revise", "test", "polling.jl"))'

after_script:  # TODO: change to after_success once https://github.com/JuliaLang/julia/issues/28306 is fixed
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Revise")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Update the documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("Revise")); include(joinpath("docs", "make.jl"))'
